name: Suying666-auto-clock-in
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 1 * * *'
jobs:
  build:
    name: Suying666-clock-in by GitHub Actions
    runs-on: ubuntu-latest

    steps:
      - name: 1. git checkout...
        uses: actions/checkout@v3

      - name: 2. setup python3...
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          check-latest: true
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: 3. do sign in...
        run: python index.py "$EMAIL" "$PASSWD" "$KEY"
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWD: ${{ secrets.PASSWD }}
          KEY: ${{ secrets.KEY }}

      # - name: 4. update github repository...
      # run: |
      # git config --global user.email "$EMAIL1"
      # git config --global user.name "bot"
      # git add .
      # git commit -m "auto-update"
      # git push -f
      # env:
      # EMAIL: ${{ secrets.EMAIL1 }}

        - name: 4. commit...
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -a -m "auto-checkin"

      - name: 5. push changes to repository...
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
